@customerId = customer1
@licenseId = license1

###
GET http://localhost:8080/

###
GET http://localhost:8080/devops/db
x-wbla-devops-api-key: SecurePassword!
Authorization: Basic userName SuperSecretPassword1234!!

###
POST http://localhost:8080/devops/db
x-wbla-devops-api-key: SecurePassword!
Authorization: Basic SecurePassword!

###
GET http://localhost:8080/license/DEMO

###
POST http://localhost:8080/license/{{licenseId}}/assign
Authorization: Basic userName SuperSecretPassword1234!!

###
POST http://localhost:8080/license/{{licenseId}}/unassign
Authorization: Basic userName SuperSecretPassword1234!!

###
POST http://localhost:8080/createDevice/{{customerId}}
deviceName: device1
deviceId: 1234567
locationId: 123
